#!/usr/bin/env -S bash ../.port_include.sh
port='freeciv'
version='3.0.9'
useconfigure='true'
configopts=(
    '--enable-client=sdl2'
    '--enable-fcmp=no'
)
files=(
    "http://files.freeciv.org/stable/freeciv-${version}.tar.xz#16c46a9c378b4a511c1e3d3a7c435a78230a432d8b852202aaf5d5d584962742"
)
depends=(
    'curl'
    'gettext'
    'libicu'
    'SDL2_gfx'
    'SDL2_image'
    'SDL2_mixer'
    'SDL2_ttf'
    'SDL2'
    'xz'
    'zstd'
)
launcher_name='Freeciv'
launcher_category='Games'
launcher_command='/usr/local/bin/freeciv-sdl2'
icon_file='windows/client.ico'
